### ISSUE TITLE
API-communication for Capture/Cancel uses config from Default-store

### ISSUE THREAD

**Issue by tobiassundgren-collector** [collector-bank/Checkout-Magento-2#17]
I think the communication with Collector for "Activate Invoice" uses config from Magento Default Config and not from Website/Store View when Capturing/Canceling invoices.

To recreate:
* Install module and setup the Collector Checkout config for a website, but not in Default config.
* Try to capture a test-order
  * In my case it didn't work and you get an error-message.

* It started working when I had entered Username, Password and Store-ID:s (not sure all was needed) in the Default config for the Magento Module.  It worked even if the Module was disabled in the Default Config.

Was using v1.0.8

**Comment by tobiassundgren-collector** [comment]
A related issue:  Testmode setting this is collected from the store 0 configuration in Validation-callback.

**Comment by kristoffer124** [comment]
This was fixed in: https://github.com/collector-bank/Checkout-Magento-2/commit/10dcbf5d85747f8a7715956e33de963a73d99788
