### ISSUE TITLE
Carrier Collector should have null check on quote ID

### ISSUE THREAD

**Issue by stefanfr** [collector-bank/Checkout-Magento-2#19]
Hi there,

In the Carrier a function is called `collectRates` where the quote Id is fetched from the first quote item in the cart. However right after logging in and merging the quote this results in a `null`
```$quoteId = $quote->getQuoteId();```

After this the `$method = $this->getMethodForQuote($quoteId);` method is called where the `$quoteId` cannot be null this causes an error right after merging the quote.

There should be a null check between both methods to avoid this error:
```
if (null === $quoteId) {
    return $result;
}
```

Could you please consider adding this null check? I'm not sure if this is reproducable via Magento itself but via the API it is.

**Comment by kristoffer124** [comment]
Hello, 

Thanks for the feedback. 
This check will be included in next release.v1.0.30.

**Comment by kristoffer124** [comment]
Added in todays release: https://github.com/collector-bank/Checkout-Magento-2/releases/tag/v1.0.30
