### ISSUE TITLE
Respond 200 if order is already handled on callback

### ISSUE THREAD

**Issue by kristoffer-webbhuset** [collector-bank/Checkout-Magento-2#3]
If order is already handled, module is answering with 400.
{
    "message": "Order already invoiced in Magento for 183.0000"
}
Respond with 200 in this case, otherwise:
"Please note the Checkout will attempt to notify the provided notification URI multiple times with increasing backoff time until a HTTP status code 200 is received in the response. Our retry mechanism is built in a way that we guarantee at-least-once-delivery and the notification URI endpoint must therefore support being called multiple times without side effects."

**Comment by davidhagg** [comment]
https://payments.collectorbank.se/docs/checkout/notificationcallback#idempotency-and-retries

**Comment by kristoffer-webbhuset** [comment]
Solved and tested in release 1.0.4
