### ISSUE TITLE
Customer Email is missing seen in logs

### ISSUE THREAD

**Issue by kristoffer-webbhuset** [collector-bank/Checkout-Magento-2#6]
Sometimes in the logs we see that place order fails with the error "Customer email is missing"
This is most likely because the address in the iframe is not in sync with the data in Magento. 

When we get a validation callback request we call place order, this then fails with "Customer email is missing". We can solve this by before placing order setting the address based on the data in the acquireCheckoutInformation.

**Comment by davidhagg** [comment]
The latest Checkout information should always be aquired from the Checkout API to know the current state. https://payments.collectorbank.se/docs/checkout/getcheckoutinformation

Please note that it is possible that this customer information might change between validation callbacks as well. 

For example if a customer is denied credit, enters new information or completely re-identifies and then tries to purchase again - then the information in Get Checkout Information will differ between the retries.

**Comment by kristoffer-webbhuset** [comment]
Solved and tested in release 1.0.4
